### ISSUE TITLE
Fix channel name in notification settings

### ISSUE THREAD

**Issue by DanKomorny** [conreality/conreality-player#4]
![a5b2c025-8608-4594-8fdd-9bf4a48e8fbe](https://user-images.githubusercontent.com/8873949/51876955-a26bf380-236a-11e9-9424-a4c48692f68f.jpg)

**Comment by artob** [comment]
This is due to the https://github.com/transistorsoft/flutter_background_geolocation plugin we use. I will inquire upstream about being able to change that label.

**Comment by artob** [comment]
This is due to the [transistorsoft/flutter_background_geolocation](https://github.com/transistorsoft/flutter_background_geolocation) plugin we use. I will inquire upstream about being able to change that label.

**Comment by artob** [comment]
This is due to the [flutter_background_geolocation](https://github.com/transistorsoft/flutter_background_geolocation) plugin we use. I will inquire upstream about being able to change that label.

**Comment by artob** [comment]
I've submitted a bug report upstream in https://github.com/transistorsoft/flutter_background_geolocation/issues/22
